Refactoring
Melkii01/tz-todo pull request #5
Opened 2024-08-29 08:45 UTC by Melkii01

2024-08-29 15:43 UTC, Melkii01 commented on projects/lib-todo/src/lib/todo/components/todo-footer/todo-footer.component.ts
> +  );
Можно оставить так, вызвать в html async

2024-08-30 03:11 UTC, tamazyanarsen requested changes

2024-08-30 03:11 UTC, tamazyanarsen commented on projects/lib-todo/src/lib/todo/components/todo-footer/todo-footer.component.ts
> +  );
оставляем

2024-08-30 03:11 UTC, tamazyanarsen commented on projects/lib-todo/src/lib/todo/components/todo-footer/todo-footer.component.ts
> +  );
можно упростить
```suggestion
  filterParam$: Observable<Params> = this.activatedRoute.queryParams.pipe(
    map((params: Params) => params[FilterNames.filter])
  );
```

2024-09-02 08:22 UTC, merged